

  CREATE TABLE "SYSTEM"."CATEGORIES" 
   (	"CATEGORYID" VARCHAR2(26 BYTE),  
	"CATEGORYNAME" VARCHAR2(26 BYTE),  
	"PARENTCATEGORY" VARCHAR2(26 BYTE),  
	"ISACTIVE" VARCHAR2(26 BYTE) 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."CATEGORIES" ADD CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("C
ATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;


  CREATE TABLE "SYSTEM"."ORDERS" 
   (	"ORDERID" NUMBER,  
	"CUSTOMER_NAME" VARCHAR2(100 BYTE),  
	"ORDER_DATE" DATE DEFAULT SYSDATE,  
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Pending',  
	"TOTAL_AMOUNT" NUMBER(10,2) 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;


  CREATE TABLE "SYSTEM"."ORDER_ITEMS" 
   (	"ORDER_ITEM_ID" NUMBER,  
	"ORDER_ID" NUMBER,  
	"PRODUCT_ID" NUMBER,  
	"QUANTITY" NUMBER NOT NULL ENABLE,  
	"UNIT_PRICE" NUMBER(10,2) NOT NULL ENABLE 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."ORDER_ITEMS" ADD PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."ORDER_ITEMS" ADD CONSTRAINT "FK_ORDER_TO_ITEMS" FOREIGN KE
Y ("ORDER_ID")
	  REFERENCES "SYSTEM"."ORDERS" ("ORDERID") ENABLE; 
ALTER TABLE "SYSTEM"."ORDER_ITEMS" ADD CONSTRAINT "FK_PRODUCT_TO_ITEMS" FOREIGN 
KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCTID") ENABLE; 


  CREATE TABLE "SYSTEM"."PRODUCTS" 
   (	"PRODUCTID" NUMBER(38,0),  
	"SKU" VARCHAR2(26 BYTE),  
	"PRODUCTNAME" VARCHAR2(26 BYTE),  
	"SUPPLIER" VARCHAR2(26 BYTE),  
	"UNITPRICE" NUMBER(38,2),  
	"UNITCOST" NUMBER(38,2),  
	"INSTOCKQTY" NUMBER(38,0),  
	"UPC" NUMBER(38,0),  
	"UNITSIZE" VARCHAR2(26 BYTE),  
	"VENDORPRODUCTCODE" VARCHAR2(26 BYTE),  
	"REORDERTHRESHOLD" NUMBER(38,0),  
	"DISCONTINUED" VARCHAR2(26 BYTE),  
	"TAXCATEGORY" VARCHAR2(26 BYTE),  
	"RESTOCKDATE" DATE,  
	"PROMOELIGIBLE" VARCHAR2(26 BYTE),  
	"NEXTRESTOCKDUE" DATE,  
	"AUTOREORDER" VARCHAR2(26 BYTE),  
	"ISACTIVE" VARCHAR2(26 BYTE),  
	"SHELFLOCATION" VARCHAR2(26 BYTE),  
	"LAST_UPDATED" TIMESTAMP (6),  
	"CATEGORY" VARCHAR2(26 BYTE) 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("PRODU
CTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_SUPPLIER" FOREIGN KE
Y ("SUPPLIER")
	  REFERENCES "SYSTEM"."VENDORS" ("SUPPLIERID") ENABLE; 
ALTER TABLE "SYSTEM"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_CATEGORY" FOREIGN KE
Y ("CATEGORY")
	  REFERENCES "SYSTEM"."CATEGORIES" ("CATEGORYID") ENABLE; 


  CREATE TABLE "SYSTEM"."PROMOTIONS" 
   (	"PROMOID" VARCHAR2(26 BYTE),  
	"PRODUCTID" NUMBER(38,0),  
	"DISCOUNTPERCENT" NUMBER(38,0),  
	"STARTDATE" DATE,  
	"ENDDATE" DATE,  
	"CHANNEL" VARCHAR2(26 BYTE) 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."PROMOTIONS" ADD CONSTRAINT "PK_PROMOTIONS" PRIMARY KEY ("P
ROMOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."PROMOTIONS" ADD CONSTRAINT "FK_PROMOTIONS_PRODUCT" FOREIGN
 KEY ("PRODUCTID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCTID") ENABLE; 


  CREATE TABLE "SYSTEM"."PURCHASE_ORDERS" 
   (	"POID" VARCHAR2(26 BYTE),  
	"SUPPLIER" VARCHAR2(26 BYTE),  
	"PRODUCTID" NUMBER(38,0),  
	"QTYORDERED" NUMBER(38,0),  
	"DATEORDERED" DATE,  
	"DATERECEIVED" DATE,  
	"STATUS" VARCHAR2(26 BYTE),  
	"STOREID" NUMBER 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."PURCHASE_ORDERS" ADD CONSTRAINT "PK_PURCHASE_ORDERS" PRIMA
RY KEY ("POID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."PURCHASE_ORDERS" ADD CONSTRAINT "FK_PURCHASE_SUPPLIER" FOR
EIGN KEY ("SUPPLIER")
	  REFERENCES "SYSTEM"."VENDORS" ("SUPPLIERID") ENABLE; 
ALTER TABLE "SYSTEM"."PURCHASE_ORDERS" ADD CONSTRAINT "FK_PURCHASE_PRODUCT" FORE
IGN KEY ("PRODUCTID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCTID") ENABLE; 
ALTER TABLE "SYSTEM"."PURCHASE_ORDERS" ADD CONSTRAINT "FK_PURCHASE_STORE" FOREIG
N KEY ("STOREID")
	  REFERENCES "SYSTEM"."STORES" ("STOREID") ENABLE; 


  CREATE TABLE "SYSTEM"."SALES_TRANSACTION" 
   (	"TRANSACTIONID" VARCHAR2(26 BYTE),  
	"DATETIME" DATE,  
	"PRODUCTID" NUMBER(38,0),  
	"QTYSOLD" NUMBER(38,0),  
	"UNITPRICE" NUMBER(38,2),  
	"TOTALPRICE" NUMBER(38,2),  
	"PAYMENTMETHOD" VARCHAR2(26 BYTE),  
	"CASHIERID" VARCHAR2(26 BYTE),  
	"PROMOID" VARCHAR2(20 BYTE),  
	"STOREID" NUMBER 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."SALES_TRANSACTION" ADD CONSTRAINT "PK_SALES_TRANSACTION" P
RIMARY KEY ("TRANSACTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."SALES_TRANSACTION" ADD CONSTRAINT "FK_SALES_PRODUCT" FOREI
GN KEY ("PRODUCTID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCTID") ENABLE; 
ALTER TABLE "SYSTEM"."SALES_TRANSACTION" ADD CONSTRAINT "FK_SALES_CASHIER" FOREI
GN KEY ("CASHIERID")
	  REFERENCES "SYSTEM"."USERS" ("USERID") ENABLE; 
ALTER TABLE "SYSTEM"."SALES_TRANSACTION" ADD CONSTRAINT "FK_SALES_PROMO" FOREIGN
 KEY ("PROMOID")
	  REFERENCES "SYSTEM"."PROMOTIONS" ("PROMOID") ENABLE; 
ALTER TABLE "SYSTEM"."SALES_TRANSACTION" ADD CONSTRAINT "FK_SALES_STORE" FOREIGN
 KEY ("STOREID")
	  REFERENCES "SYSTEM"."STORES" ("STOREID") ENABLE NOVALIDATE; 


  CREATE TABLE "SYSTEM"."STORES" 
   (	"STOREID" NUMBER,  
	"STORE_NAME" VARCHAR2(100 BYTE),  
	"LOCATION" VARCHAR2(100 BYTE) 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."STORES" ADD CONSTRAINT "PK_STORES" PRIMARY KEY ("STOREID")

  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;


  CREATE TABLE "SYSTEM"."STORE_INVENTORY" 
   (	"PRODUCTID" NUMBER(38,0),  
	"QTYONHAND" NUMBER(38,0),  
	"REORDERTHRESHOLD" NUMBER(38,0),  
	"LASTRESTOCKDATE" DATE,  
	"STOREID" NUMBER 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."STORE_INVENTORY" ADD CONSTRAINT "PK_STORE_INVENTORY" PRIMA
RY KEY ("STOREID", "PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."STORE_INVENTORY" ADD CONSTRAINT "FK_INVENTORY_PRODUCT" FOR
EIGN KEY ("PRODUCTID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCTID") ENABLE; 
ALTER TABLE "SYSTEM"."STORE_INVENTORY" ADD CONSTRAINT "FK_INVENTORY_STORE" FOREI
GN KEY ("STOREID")
	  REFERENCES "SYSTEM"."STORES" ("STOREID") ENABLE NOVALIDATE; 


  CREATE TABLE "SYSTEM"."USERS" 
   (	"USERID" VARCHAR2(26 BYTE),  
	"NAME" VARCHAR2(26 BYTE),  
	"ROLE" VARCHAR2(26 BYTE),  
	"USERNAME" VARCHAR2(26 BYTE),  
	"PASSWORDHASH" VARCHAR2(128 BYTE),  
	"PERMISSIONS" VARCHAR2(26 BYTE),  
	"STOREID" NUMBER 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "FK_USER_STORE" FOREIGN KEY ("STOREI
D")
	  REFERENCES "SYSTEM"."STORES" ("STOREID") ENABLE; 


  CREATE TABLE "SYSTEM"."VENDORS" 
   (	"SUPPLIERID" VARCHAR2(26 BYTE),  
	"NAME" VARCHAR2(26 BYTE),  
	"CONTACTEMAIL" VARCHAR2(128 BYTE),  
	"PHONE" VARCHAR2(26 BYTE),  
	"PAYMENTTERMS" VARCHAR2(26 BYTE),  
	"DELIVERYDAYS" VARCHAR2(26 BYTE) 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
ALTER TABLE "SYSTEM"."VENDORS" ADD CONSTRAINT "PK_VENDORS" PRIMARY KEY ("SUPPLIE
RID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

